/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 16-Oct-2016 1:13:36 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_dish_ingredients_dishes]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dish_ingredients] DROP CONSTRAINT [FK_dish_ingredients_dishes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_dish_ingredients_ingredients]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dish_ingredients] DROP CONSTRAINT [FK_dish_ingredients_ingredients]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ingredients_measurementunits]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ingredients] DROP CONSTRAINT [FK_ingredients_measurementunits]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_movements_movementconpects]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [movements] DROP CONSTRAINT [FK_movements_movementconpects]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_movements_stock]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [movements] DROP CONSTRAINT [FK_movements_stock]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_movements_warehouses]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [movements] DROP CONSTRAINT [FK_movements_warehouses]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_order_dishes_dishes]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [order_dishes] DROP CONSTRAINT [FK_order_dishes_dishes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_order_dishes_orders]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [order_dishes] DROP CONSTRAINT [FK_order_dishes_orders]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_stock_ingredients]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [stock] DROP CONSTRAINT [FK_stock_ingredients]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_stock_warehouses]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [stock] DROP CONSTRAINT [FK_stock_warehouses]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dish_ingredients]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dish_ingredients]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dishes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dishes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ingredients]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ingredients]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[measurementunits]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [measurementunits]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[movementconpects]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [movementconpects]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[movements]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [movements]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[order_dishes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [order_dishes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[orders]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [orders]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[stock]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [stock]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[warehouses]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [warehouses]
GO

/* Create Tables */

CREATE TABLE [dish_ingredients]
(
	[ing_id] int NOT NULL,
	[dis_id] int NOT NULL,
	[dis_ing_quantity] int NOT NULL
)
GO

CREATE TABLE [dishes]
(
	[dis_id] int NOT NULL,
	[dis_name] varchar(50) NOT NULL,
	[dis_description] text NOT NULL,
	[dis_price] money NOT NULL
)
GO

CREATE TABLE [ingredients]
(
	[ing_id] int NOT NULL,
	[ing_description] varchar(50) NOT NULL,
	[mu] char(5) NOT NULL
)
GO

CREATE TABLE [measurementunits]
(
	[meu_id] char(5) NOT NULL,
	[meu_description] varchar(50) NOT NULL
)
GO

CREATE TABLE [movementconpects]
(
	[mco_id] char(3) NOT NULL,
	[mco_description] varchar(50) NOT NULL
)
GO

CREATE TABLE [movements]
(
	[mov_id] int NOT NULL IDENTITY (1, 1),
	[mov_date] datetime NOT NULL,
	[mov_quantity] int NOT NULL,
	[mov_id_warehouse] char(3) NOT NULL,
	[mov_id_stock_ingredient] int NOT NULL,
	[mov_concept] char(3) NOT NULL
)
GO

CREATE TABLE [order_dishes]
(
	[dis_id] int NOT NULL,
	[ord_id] int NOT NULL,
	[ord_dis_quantity] int NOT NULL
)
GO

CREATE TABLE [orders]
(
	[ord_id] int NOT NULL,
	[ord_date] datetime NOT NULL,
	[ord_subtotal] money NOT NULL,
	[ord_iva] money NOT NULL,
	[ord_total] money NOT NULL
)
GO

CREATE TABLE [stock]
(
	[sto_id] int NOT NULL,
	[sto_id_ing] int NOT NULL,
	[war_id] char(3) NOT NULL,
	[sto_quantity] int NOT NULL
)
GO

CREATE TABLE [warehouses]
(
	[war_id] char(3) NOT NULL,
	[war_name] varchar(50) NOT NULL,
	[war_type] char(1) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dish_ingredients] 
 ADD CONSTRAINT [PK_dish_ingredients]
	PRIMARY KEY CLUSTERED ([dis_id] ASC,[ing_id] ASC)
GO

ALTER TABLE [dishes] 
 ADD CONSTRAINT [PK_dishes]
	PRIMARY KEY CLUSTERED ([dis_id] ASC)
GO

ALTER TABLE [ingredients] 
 ADD CONSTRAINT [PK_ingredients]
	PRIMARY KEY CLUSTERED ([ing_id] ASC)
GO

ALTER TABLE [measurementunits] 
 ADD CONSTRAINT [PK_measurementunits]
	PRIMARY KEY CLUSTERED ([meu_id] ASC)
GO

ALTER TABLE [movementconpects] 
 ADD CONSTRAINT [PK_movementconpects]
	PRIMARY KEY CLUSTERED ([mco_id] ASC)
GO

ALTER TABLE [movements] 
 ADD CONSTRAINT [PK_movements]
	PRIMARY KEY CLUSTERED ([mov_id] ASC)
GO

ALTER TABLE [order_dishes] 
 ADD CONSTRAINT [PK_order_dishes]
	PRIMARY KEY CLUSTERED ([dis_id] ASC,[ord_id] ASC)
GO

ALTER TABLE [orders] 
 ADD CONSTRAINT [PK_orders]
	PRIMARY KEY CLUSTERED ([ord_id] ASC)
GO

ALTER TABLE [stock] 
 ADD CONSTRAINT [PK_stock]
	PRIMARY KEY CLUSTERED ([sto_id] ASC)
GO

ALTER TABLE [warehouses] 
 ADD CONSTRAINT [PK_warehouses]
	PRIMARY KEY CLUSTERED ([war_id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [dish_ingredients] ADD CONSTRAINT [FK_dish_ingredients_dishes]
	FOREIGN KEY ([dis_id]) REFERENCES [dishes] ([dis_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dish_ingredients] ADD CONSTRAINT [FK_dish_ingredients_ingredients]
	FOREIGN KEY ([ing_id]) REFERENCES [ingredients] ([ing_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ingredients] ADD CONSTRAINT [FK_ingredients_measurementunits]
	FOREIGN KEY ([mu]) REFERENCES [measurementunits] ([meu_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [movements] ADD CONSTRAINT [FK_movements_movementconpects]
	FOREIGN KEY ([mov_concept]) REFERENCES [movementconpects] ([mco_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [movements] ADD CONSTRAINT [FK_movements_stock]
	FOREIGN KEY ([mov_id_stock_ingredient]) REFERENCES [stock] ([sto_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [movements] ADD CONSTRAINT [FK_movements_warehouses]
	FOREIGN KEY ([mov_id_warehouse]) REFERENCES [warehouses] ([war_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [order_dishes] ADD CONSTRAINT [FK_order_dishes_dishes]
	FOREIGN KEY ([dis_id]) REFERENCES [dishes] ([dis_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [order_dishes] ADD CONSTRAINT [FK_order_dishes_orders]
	FOREIGN KEY ([ord_id]) REFERENCES [orders] ([ord_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [stock] ADD CONSTRAINT [FK_stock_ingredients]
	FOREIGN KEY ([sto_id_ing]) REFERENCES [ingredients] ([ing_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [stock] ADD CONSTRAINT [FK_stock_warehouses]
	FOREIGN KEY ([war_id]) REFERENCES [warehouses] ([war_id]) ON DELETE No Action ON UPDATE No Action
GO
